version: "3"
services: 
  web:
    image: test-node
    ports: 
      - "3003:3001"
    networks: 
      - webnet
    
    environment: 
     
      MONGO_HOST: mongo
      JWT_SECRET: "secret"
    depends_on: 
      - mongo
      
  mongo:
    image: "mongo:4"
    networks: 
      - webnet
    volumes:
      - ./data:/data/db
    ports: 
      - "27018:27017"
  
  nginx:
    image: "nginx:1.16.1"
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    
    ports:
      - "3001:80"
    depends_on: 
      - web
    command: /bin/bash -c "envsubst  < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks: 
      - webnet

networks: 
  webnet: